### PR TITLE
Fix getPageProps

### PR DESCRIPTION
**Pull request by physikerwelt**
PageProps has been converted to a service.

Bug: T289544

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
> Call to undefined method `MediaWiki\MediaWikiServices::getPageProps`

So this was added som time after 1.35?

**Comment by physikerwelt** [comment]
Yes, in 1.36 I think. See

https://phabricator.wikimedia.org/T289544

for patch variants with if function_exists.

**Comment by Seb35** [comment]
A few remarks:
* the issue #67 has been opened related to this PR
* tested with 1.40 + PHP 7.4, it works well :)
* in the code, there is `$this->services` available in the object, I guess it would be better to use it
* MW 1.35 has end of life in [November 2023](https://www.mediawiki.org/wiki/Version_lifecycle) and it is documented in [extension.json that 1.35 is supported](https://github.com/SemanticMediaWiki/SemanticDrilldown/blob/8262c2a17d5eac3db68f1cc909df92f455740a5e/extension.json#L14), so it might be better to support it with `method_exists` or increase the version to 1.36 in extension.json

**Comment by gesinn-it-gea** [comment]
We will have a look at this later today. I'd like to keep it compatible with 1.35 for a while.

**Comment by gesinn-it-wam** [comment]
To speed things up I will merge the PR and add the MW version switch in a separate commit

**Pull request merged**
