### PR TITLE
overwrite getQueryInfo instead of getSQL

### PR DESCRIPTION
**Pull request by YvarRavy**
i just converted the sqlProvider::getSQL to this to use correct way of accessing the DB
original issue: https://github.com/SemanticMediaWiki/SemanticDrilldown/issues/73

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
@YvarRavy can you try to run CI locally before pushing changes? Simply run `make ci`.

**Comment by YvarRavy** [comment]
> @YvarRavy can you try to run CI locally before pushing changes? Simply run `make ci`.

apolegies i am done now will do it next time

**Comment by YOUR1** [comment]
Can you recheck @gesinn-it-gea?

**Comment by YvarRavy** [comment]
i did use https://github.com/SemanticMediaWiki/SemanticDrilldown/pull/52 to test my changes. because without it seemed to go wrong

**Comment by YOUR1** [comment]
@gesinn-it-gea I do wonder why this takes so long to get approved. It fixes things, right? :-)

**Comment by gesinn-it-gea** [comment]
CI is not working properly at the moment. We need to fix that first.

**Comment by YOUR1** [comment]
In this fix, or on the repository it self? What can we do to speed up this process, since the deprecated warnings are filling up our logs :>

**Pull request merged**
